// <auto-generated />
using Desafio.s2.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Desafio.s2.Data.Migrations.ApplicationData
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Desafio.s2.Domain.Amigos.Amigo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Excluido");

                    b.Property<Guid>("IdUsuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Amigo");
                });

            modelBuilder.Entity("Desafio.s2.Domain.Jogos.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Desafio.s2.Domain.Jogos.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoriaId");

                    b.Property<Guid?>("EmprestadoParaId");

                    b.Property<bool>("Excluido");

                    b.Property<Guid>("IdUsuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ThumbnailCapaJogo")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EmprestadoParaId");

                    b.ToTable("Jogo");
                });

            modelBuilder.Entity("Desafio.s2.Domain.Jogos.Jogo", b =>
                {
                    b.HasOne("Desafio.s2.Domain.Jogos.Categoria", "Categoria")
                        .WithMany("Jogos")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Desafio.s2.Domain.Amigos.Amigo", "EmprestadoPara")
                        .WithMany("Jogos")
                        .HasForeignKey("EmprestadoParaId");
                });
#pragma warning restore 612, 618
        }
    }
}
